In [1]:
from json_tool import *
from filter_tool import *

### 기존의 jsonl 형태로 저장된 코드들을 데이터 프레임 형태로 변환한다.

In [2]:
#jsonl_file = "code_source/Codes2_Codes3_base.jsonl"
jsonl_file = "code_source/Code_base_example.jsonl"
df = read_jsonl_file(jsonl_file)  # lines=True는 JSONL 파일용, False는 JSON 파일용
df

,file_name,line_count,code
0,010-TestCase_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
1,020-TestCase-2_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
2,030-Asn-Require-Check_function_1.cpp,3,"string one() {\n return ""1"";\n}"
3,110-Fix-ClassFixture_function_1.cpp,3,DBConnection createConnection( std::string con...
4,110-Fix-ClassFixture_function_2.cpp,6,bool executeSQL( std::string const & /*query*/...
...,...,...,...
18942,xchar_function_3.cpp,3,"void print(std::FILE* f, wformat_string<T...> ..."
18943,xchar_function_4.cpp,3,"void print(wformat_string<T...> fmt, T&&... ar..."
18944,xchar_function_5.cpp,3,"void println(std::FILE* f, wformat_string<T......"
18945,xchar_function_6.cpp,3,"void println(wformat_string<T...> fmt, T&&... ..."
18946,xmrx_function_1.cpp,7,size_t xmrx(size_t x)\n{\n x ^= x >> 32;\n ...

### 500 라인 이상인 코드는 모두 제거한다.

In [ ]:
lineno = 500
df2 = filter_by_numline_limit(df, lineno) # OO 라인 이하인 것은 전부 제거
df2

,file_name,line_count,code
0,010-TestCase_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
1,020-TestCase-2_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
2,030-Asn-Require-Check_function_1.cpp,3,"string one() {\n return ""1"";\n}"
3,110-Fix-ClassFixture_function_1.cpp,3,DBConnection createConnection( std::string con...
4,110-Fix-ClassFixture_function_2.cpp,6,bool executeSQL( std::string const & /*query*/...
...,...,...,...
18934,xchar_function_3.cpp,3,"void print(std::FILE* f, wformat_string<T...> ..."
18935,xchar_function_4.cpp,3,"void print(wformat_string<T...> fmt, T&&... ar..."
18936,xchar_function_5.cpp,3,"void println(std::FILE* f, wformat_string<T......"
18937,xchar_function_6.cpp,3,"void println(wformat_string<T...> fmt, T&&... ..."
18938,xmrx_function_1.cpp,7,size_t xmrx(size_t x)\n{\n x ^= x >> 32;\n ...

In [ ]:
minlineno = 3
df2 = filter_by_numline_over(df2, minlineno) # OO 라인 이하인것은 전부 제거거
df2

,file_name,line_count,code
0,010-TestCase_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
1,020-TestCase-2_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
2,110-Fix-ClassFixture_function_2.cpp,6,bool executeSQL( std::string const & /*query*/...
3,210-Evt-EventListeners_function_10.cpp,8,"void print( std::ostream& os, int const level,..."
4,210-Evt-EventListeners_function_11.cpp,5,"void print( std::ostream& os, int const level,..."
...,...,...,...
13476,xchar-test_function_7.cpp,17,wstring system_wcsftime(const std::wstring& fo...
13477,xchar-test_function_8.cpp,16,endif\n for (const auto& spec : spec_list) {\...
13478,xchar-test_function_9.cpp,7,iterator parse(\n basic_format_parse_cont...
13479,xchar_function_1.cpp,7,"void vprint(std::FILE* f, wstring_view fmt, wf..."
13480,xmrx_function_1.cpp,7,size_t xmrx(size_t x)\n{\n x ^= x >> 32;\n ...

### 코드 중에서 C/C++ 함수 형태가 아닌 코드들이 있다. 이러한 코드들은 제거한다

In [5]:
df3 = filter_by_non_cpp_functions(df2) # C/C++가 아닌 엔트리는 제거
df3

100%|██████████| 13481/13481 [00:00<00:00, 207829.76it/s]

,file_name,line_count,code
0,010-TestCase_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
1,020-TestCase-2_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
2,110-Fix-ClassFixture_function_2.cpp,6,bool executeSQL( std::string const & /*query*/...
3,210-Evt-EventListeners_function_10.cpp,8,"void print( std::ostream& os, int const level,..."
4,210-Evt-EventListeners_function_11.cpp,5,"void print( std::ostream& os, int const level,..."
...,...,...,...
11792,xchar-test_function_5.cpp,11,FMT_USE_USER_DEFINED_LITERALS\nTEST(xchar_test...
11793,xchar-test_function_6.cpp,9,FMT_USE_USER_DEFINED_LITERALS\n\nTEST(xchar_te...
11794,xchar-test_function_8.cpp,16,endif\n for (const auto& spec : spec_list) {\...
11795,xchar_function_1.cpp,7,"void vprint(std::FILE* f, wstring_view fmt, wf..."
11796,xmrx_function_1.cpp,7,size_t xmrx(size_t x)\n{\n x ^= x >> 32;\n ...

### 코드 중에서 파서의 오류로 함수가 1개 존재하는 것이 아니라 2개 이상 존재할 수 있다. 이러한 경우는 제거한다. (함수 1개만 허용)

In [6]:
df4 = filter_by_removing_multiple_functions(df3) # 코드에 함수가 여러개 있는 것은 제거
df4

100%|██████████| 11797/11797 [00:00<00:00, 54071.70it/s]

,file_name,line_count,code
0,010-TestCase_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
1,020-TestCase-2_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
2,110-Fix-ClassFixture_function_2.cpp,6,bool executeSQL( std::string const & /*query*/...
3,210-Evt-EventListeners_function_10.cpp,8,"void print( std::ostream& os, int const level,..."
4,210-Evt-EventListeners_function_11.cpp,5,"void print( std::ostream& os, int const level,..."
...,...,...,...
11211,xchar-test_function_5.cpp,11,FMT_USE_USER_DEFINED_LITERALS\nTEST(xchar_test...
11212,xchar-test_function_6.cpp,9,FMT_USE_USER_DEFINED_LITERALS\n\nTEST(xchar_te...
11213,xchar-test_function_8.cpp,16,endif\n for (const auto& spec : spec_list) {\...
11214,xchar_function_1.cpp,7,"void vprint(std::FILE* f, wstring_view fmt, wf..."
11215,xmrx_function_1.cpp,7,size_t xmrx(size_t x)\n{\n x ^= x >> 32;\n ...

### 코드의 라인 수 뿐만 아니라 토큰 수도 제한을 둔다. 5000개의 토근 이상인 경우, LLM이 처리하기에는 부담스러우므로 제거한다.

In [7]:
tokenno = 5000
df5 = filter_by_numtoken_limit(df4, tokenno)
df5

100%|██████████| 11216/11216 [00:02<00:00, 5024.05it/s]

,file_name,line_count,code
0,010-TestCase_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
1,020-TestCase-2_function_1.cpp,4,int Factorial( int number ) {\n return numbe...
2,110-Fix-ClassFixture_function_2.cpp,6,bool executeSQL( std::string const & /*query*/...
3,210-Evt-EventListeners_function_10.cpp,8,"void print( std::ostream& os, int const level,..."
4,210-Evt-EventListeners_function_11.cpp,5,"void print( std::ostream& os, int const level,..."
...,...,...,...
11211,xchar-test_function_5.cpp,11,FMT_USE_USER_DEFINED_LITERALS\nTEST(xchar_test...
11212,xchar-test_function_6.cpp,9,FMT_USE_USER_DEFINED_LITERALS\n\nTEST(xchar_te...
11213,xchar-test_function_8.cpp,16,endif\n for (const auto& spec : spec_list) {\...
11214,xchar_function_1.cpp,7,"void vprint(std::FILE* f, wstring_view fmt, wf..."
11215,xmrx_function_1.cpp,7,size_t xmrx(size_t x)\n{\n x ^= x >> 32;\n ...

### 필터된 jsonl 파일을 저장한다.

In [8]:
output_jsonl_file = "code_filtered/Code_filtered_example.jsonl"
convert_df_to_jsonl(df5, output_jsonl_file)

JSONL 파일이 생성되었습니다!